version: '3.9'
services:
  search_engine:
    image: getmeili/meilisearch:v0.20.0
    restart: always
    volumes:
      - ./meilidata:/data.ms
    environment:
      MEILI_ENV: development
      MEILI_HTTP_PAYLOAD_SIZE_LIMIT: '104857600'
    ports:
      - 7700:7700
